import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true}),url=process.env.TEST_URL||'http://127.0.0.1:5177/home.html',errors=[];
const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));
await page.goto(url);await page.waitForSelector('.hardware-ready');
const hero=page.locator('.hardware-canvas');
await page.locator('[data-action=explode]').click();await expect(hero).toHaveAttribute('data-explode','1.00');
for(const air of ['good','attention','poor']){await page.locator(`[data-air=${air}]`).filter({has:page.locator('span')}).count();await page.locator(`button[data-air=${air}]`).click();await expect(hero).toHaveAttribute('data-air',air)}
await page.locator('[data-action=explode]').click();await expect(hero).toHaveAttribute('data-explode','0.00');await expect(hero).toHaveAttribute('data-flow','true');
await page.locator('#size').scrollIntoViewIfNeeded();await expect(page.locator('.scale-canvas')).toHaveAttribute('data-reveal','1.000');
await page.getByRole('button',{name:'Replay the size comparison reveal'}).click();const samples=[];
for(let i=0;i<6;i++){await page.waitForTimeout(420);samples.push(await page.locator('.scale-canvas').getAttribute('data-reveal'));await page.locator('.scale-stage').screenshot({path:`captures/scale/motion-${i}.png`})}
if(new Set(samples).size<3)throw Error('Reveal did not progress');
await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(300);await page.locator('#size').scrollIntoViewIfNeeded();await expect(page.locator('.scale-canvas')).toHaveAttribute('data-reveal','1.000');
await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.locator('#size').scrollIntoViewIfNeeded();await expect(page.locator('.scale-canvas')).toHaveAttribute('data-reveal','1.000');await page.locator('[data-mode=footprint]').click();await expect(page.locator('.scale-canvas')).toHaveAttribute('data-view','1.000');await page.locator('#size').screenshot({path:'captures/scale/reduced-motion.png'});await page.locator('[data-mode=compare]').click();await expect(page.locator('.scale-canvas')).toHaveAttribute('data-view','0.000');
await page.route('**/showcase/aircube-base.glb',r=>r.abort());await page.reload();await page.locator('#size').scrollIntoViewIfNeeded();await expect(page.locator('.scale-status')).toContainText('Still views');await expect(page.locator('.scale-poster')).toBeVisible();if(!await page.locator('.scale-poster').evaluate(i=>i.naturalWidth>0))throw Error('Missing poster');await page.locator('[data-mode=footprint]').click();await page.waitForTimeout(200);await page.locator('#size').screenshot({path:'captures/scale/fallback.png'});
const noGL=await browser.newPage({viewport:{width:390,height:844}});noGL.on('pageerror',e=>errors.push(e.message));await noGL.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...a){return t.startsWith('webgl')?null:get.call(this,t,...a)}});await noGL.goto(url);await noGL.locator('#size').scrollIntoViewIfNeeded();await expect(noGL.locator('.scale-status')).toContainText('Still views');if(!await noGL.locator('.scale-poster').evaluate(i=>i.naturalWidth>0))throw Error('Missing mobile fallback');await noGL.locator('#size').screenshot({path:'captures/scale/no-webgl-mobile.png'});
await browser.close();if(errors.length)throw Error(errors.join('\n'));console.log('Passed hero isolation, all air states, separation/reassembly, persistent airflow, animated reveal samples, one-time entry, reduced motion, model failure and unavailable WebGL. Reveal samples:',samples);
