import fs from 'node:fs';import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.stack));const url=process.env.TEST_URL||'http://localhost:5177';fs.mkdirSync('captures',{recursive:true});
await page.goto(url);await page.waitForSelector('.hardware-ready');await page.waitForTimeout(1000);
const canvas=page.locator('.hardware-canvas');const snap=async name=>page.screenshot({path:`captures/${name}.png`});
await snap('desktop-assembled');await page.locator('[data-action=explode]').click();await expect(canvas).toHaveAttribute('data-explode','1.00',{timeout:10000});await snap('desktop-exploded');
await page.locator('[data-anchor=U2]').click();await expect(page.locator('.hardware-story')).toHaveAttribute('data-selected','U2');await expect(page.locator('#playground')).not.toHaveAttribute('open','');
await page.locator('[data-action=airflow]').click();await expect(canvas).toHaveAttribute('data-flow','true');await snap('desktop-airflow');
await page.locator('[data-action=explode]').click();await expect(canvas).toHaveAttribute('data-explode','0.00',{timeout:10000});
for(const state of ['good','attention','poor']){await page.locator(`button[data-air=${state}]`).click();await page.waitForTimeout(1000);await expect(canvas).toHaveAttribute('data-air',state);await snap('desktop-'+state);}
await page.locator('[data-action=scroll]').click();for(const progress of [0,.25,.5,.75,1,.5,0]){await page.evaluate(p=>{const s=document.querySelector('.hardware-story');scrollTo(0,s.offsetTop+p*(s.offsetHeight-innerHeight))},progress);await page.waitForTimeout(700);await expect(canvas).toHaveAttribute('data-air','poor');if(progress===.5)await snap('scroll-middle');}
await expect(canvas).toHaveAttribute('data-explode','0.00',{timeout:10000});
await page.locator('button[data-air=good]').focus();await page.keyboard.press('Enter');await expect(page.locator('button[data-air=good]')).toHaveAttribute('aria-pressed','true');
const rect=await page.locator('.hardware-canvas canvas').boundingBox();await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.5);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.5+80,rect.y+rect.height*.5,{steps:10});await page.mouse.up();await page.locator('[data-action=reset]').click();
const perf=await page.evaluate(async()=>{const intervals=[];let last=performance.now();for(let i=0;i<60;i++){await new Promise(requestAnimationFrame);const now=performance.now();intervals.push(now-last);last=now}return {medianFrameMs:intervals.sort((a,b)=>a-b)[30],...document.querySelector('.hardware-canvas').dataset}});console.log('Desktop headless sample',perf);
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(500);await snap('mobile-assembled');await page.locator('[data-action=explode]').click();await expect(canvas).toHaveAttribute('data-explode','1.00',{timeout:10000});await page.locator('.hardware-visual').screenshot({path:'captures/mobile-exploded.png'});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForSelector('.hardware-ready');await page.locator('[data-action=explode]').click();await expect(canvas).toHaveAttribute('data-explode','1.00');await page.locator('button[data-air=poor]').click();await expect(canvas).toHaveAttribute('data-air','poor');await snap('reduced-motion');
await page.route('**/showcase/aircube-base.glb',r=>r.abort());await page.reload();await page.waitForSelector('.hardware-unavailable');await expect(page.locator('.hardware-poster')).toBeVisible();await expect(page.locator('.hardware-poster')).toHaveJSProperty('naturalWidth',await page.locator('.hardware-poster').evaluate(i=>i.naturalWidth));if(!await page.locator('.hardware-poster').evaluate(i=>i.naturalWidth>0))throw Error('Missing poster');await snap('fallback');
const unavailable=await browser.newPage({viewport:{width:1440,height:900}});await unavailable.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.startsWith('webgl'))return null;return original.call(this,type,...args)}});await unavailable.goto(url);await unavailable.waitForSelector('.hardware-unavailable');await unavailable.screenshot({path:'captures/no-webgl.png'});
if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync('captures/performance.json',JSON.stringify(perf,null,2));console.log('Passed: states, separation, airflow, reverse scroll, selection, keyboard, drag/reset, mobile, reduced motion, model failure, WebGL failure.');await browser.close();
