import { chromium } from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.TEST_URL||'http://localhost:5173');
await page.locator('#playground > summary').click();
await page.locator('#pcb .footprint').first().waitFor();
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'U7 ESP32-H2-MINI-1'}).click();
await page.locator('#inspector').getByText('COMPONENT INSPECTOR').waitFor();
await page.getByRole('button',{name:'U7 ESP32-H2-MINI-1'}).click();
if(await page.locator('.part.selected').count()||await page.locator('#clear-component').count())throw Error('Clicking selected component did not deselect');
await page.getByRole('button',{name:'U7 ESP32-H2-MINI-1'}).click();
await page.getByRole('button',{name:'Clear component selection'}).click();
if(await page.locator('.part.selected').count())throw Error('Clear selection failed');
await page.getByRole('button',{name:'U7 ESP32-H2-MINI-1'}).click();
await page.locator('#net').selectOption({label:'GND'});
await page.getByRole('tab',{name:'Air & LEDs'}).click();
await page.locator('#model').selectOption('pro');
await page.getByRole('button',{name:'Busy room'}).click();
if(await page.locator('#rating').textContent()!=='Poor')throw Error('Busy-room simulation failed');
await page.getByRole('button',{name:'Fresh air'}).click();
await page.getByRole('button',{name:'Back',exact:true}).click();
await page.getByRole('button',{name:'Front',exact:true}).click();
await page.getByRole('button',{name:'Reset simulation'}).click();
await page.locator('#net').selectOption('');
await page.screenshot({path:'/tmp/aircube-desktop.png',fullPage:true});
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export scenario'}).click();await download;
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/aircube-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
if(errors.length)throw Error(errors.join('\n'));
console.log('Browser checks passed: component selection, nets, scenarios, model switch, board sides, export, mobile layout.');
await browser.close();
