import './style.css';
import {mountShowcase} from './showcase/index.js';
import {simulate} from './simulation.js';
import {mountDesignLab} from './design-lab.js';
import {designHighlights,highlightOverlay} from './design-highlights.js';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const board=await fetch('/board.json').then(r=>{if(!r.ok)throw Error('Board could not be loaded');return r.json()});
const defaults={tvoc:120,co2:650,brightness:75,model:'base',power:true};
let state={...defaults};try{state={...state,...JSON.parse(localStorage.getItem('aircube-sim')||'{}')}}catch{}
let designKind=null;
let selected=null,net='',side='F.Cu',zoom=1,pan=[0,0],showTracks=true,showLabels=true,showZones=false;
const parts=board.components.filter(c=>!c.ref.includes('*')).sort((a,b)=>a.ref.localeCompare(b.ref,undefined,{numeric:true}));
$('#app').innerHTML=`<header><a class="brand" href="/"><strong>noware</strong><span> / </span><span>Hardware playground</span></a><div class="header-right"><span class="live-dot"></span> LOCAL SIMULATION <a class="github" href="/dashboard/">Live dashboard</a> <button id="signout" class="signout">Sign out</button> <a class="github" href="https://github.com/hyperchi/noware-exploer" target="_blank" rel="noreferrer">GitHub ↗</a></div></header>
<div class="intro"><div><div class="eyebrow">EXPLORE · UNDERSTAND · EXPERIMENT</div><h1>A little board. A lot to explore.</h1><p>Your hardware, with room to play. Inspect a part or change the air around it.</p></div><div class="intro-actions"><button id="open-library" class="library-open">▦ Component library</button><button id="export" class="primary">↓ Export scenario</button></div></div>
<main><aside class="parts-panel"><div class="panel-heading">Components <span>${parts.length}</span></div><div class="search-wrap"><input id="search" placeholder="Search parts or values…" aria-label="Search components"></div><div class="part-list" id="part-list"></div><div class="source-note"><span class="tiny-label">SOURCE BOARD</span><strong>AirCube v1.1 · Base</strong><span>KiCad coordinates & connectivity</span><a href="https://github.com/hyperchi/AirCube/tree/${board.commit}/kicad" target="_blank" rel="noreferrer">View original hardware ↗</a></div></aside>
<section class="workspace"><div class="board-toolbar"><div class="segmented"><button id="front" class="active">Front</button><button id="back">Back</button></div><label><input id="tracks" type="checkbox" checked> Traces</label><label><input id="labels" type="checkbox" checked> Labels</label><label><input id="zones" type="checkbox"> Copper fill</label><button id="fit" title="Reset zoom and pan">↗ Fit</button></div><div class="board-stage"><div class="stage-caption"><span class="live-dot"></span> ACTUAL PCB <span>45 × 45 mm</span></div><svg id="pcb" viewBox="17 34 59 59" role="img" aria-label="Interactive noware printed circuit board"></svg><div class="board-hint">Click to inspect · Click again or Escape to clear · Drag to pan</div><div class="zoom-controls"><button id="minus" aria-label="Zoom out">−</button><span id="zoom">100%</span><button id="plus" aria-label="Zoom in">+</button></div></div><div class="net-bar"><span>⌁</span><select id="net" aria-label="Highlight a net"><option value="">Highlight a net…</option>${Object.entries(board.nets).filter(([id])=>id!=='0').map(([id,name])=>`<option value="${id}">${esc(name)}</option>`).join('')}</select><span id="net-count">${board.tracks.length} routed traces · ${board.vias.length} vias</span></div><div id="design-board-note" hidden aria-live="polite"></div><div id="inspector"></div></section>
<aside class="simulation"><div class="panel-heading">The air around it <span class="badge">SIMULATOR</span></div><p class="sim-intro">Move a slider. See how your board responds.</p><div class="model-label">Simulated model <select id="model"><option value="base">noware Base</option><option value="pro">noware Pro</option></select></div><div id="model-comparison"></div><div class="led-card"><div class="led-orb" id="led"></div><div><span class="tiny-label">PREDICTED LED</span><h2 id="rating"></h2><span id="driver"></span></div></div><div class="presets"><button data-preset="fresh">Fresh air</button><button data-preset="busy">Busy room</button><button data-preset="cooking">Cooking</button></div><div id="sliders"></div><div class="metrics"><div><span>VOC level</span><strong id="voc"></strong></div><div><span>CO₂ level</span><strong id="carbon"></strong></div></div><label class="power"><span>USB power <small>Simulated on / off</small></span><input type="checkbox" id="power" role="switch"></label><div class="sim-note" id="sim-note"></div><button id="reset" class="reset">↺ Reset simulation</button></aside></main>
<footer><span>Built from real hardware. Made for curiosity. Made in America.</span><div><a href="/source/AirCube.kicad_pcb" download>↓ KiCad PCB</a><a href="/source/AirCube.kicad_sch" download>↓ Schematic</a><span>Source ${board.commit.slice(0,7)}</span></div></footer>`;
function list(query=''){ $('#part-list').innerHTML=parts.filter(c=>(c.ref+' '+c.value).toLowerCase().includes(query.toLowerCase())).map(c=>`<button class="part ${selected===c?'selected':''}" data-ref="${esc(c.ref)}"><span class="part-icon">${c.ref.startsWith('U')?'▦':c.ref.startsWith('LED')?'☼':c.ref.startsWith('C')?'⊣':'⌁'}</span><span><strong>${esc(c.ref)}</strong><small>${esc(c.value)}</small></span><span class="part-arrow">↗</span></button>`).join('')||'<p class="empty">No matching components.</p>'; document.querySelectorAll('[data-ref]').forEach(el=>el.onclick=()=>select(parts.find(c=>c.ref===el.dataset.ref),true)); }
function arc(s){const [x1,y1]=s.start,[x2,y2]=s.mid,[x3,y3]=s.end,d=2*(x1*(y2-y3)+x2*(y3-y1)+x3*(y1-y2));if(Math.abs(d)<1e-8)return `M${s.start} L${s.end}`;const a=x1*x1+y1*y1,b=x2*x2+y2*y2,c=x3*x3+y3*y3,cx=(a*(y2-y3)+b*(y3-y1)+c*(y1-y2))/d,cy=(a*(x3-x2)+b*(x1-x3)+c*(x2-x1))/d,r=Math.hypot(x1-cx,y1-cy);const angle=(x,y)=>Math.atan2(y-cy,x-cx),norm=v=>(v+Math.PI*4)%(Math.PI*2),span=norm(angle(x3,y3)-angle(x1,y1)),mid=norm(angle(x2,y2)-angle(x1,y1)),sweep=mid<span?1:0;return `M${s.start} A${r},${r} 0 ${(sweep?span:2*Math.PI-span)>Math.PI?1:0} ${sweep} ${s.end}`;}
function shape(s,extra=''){if(s.type==='arc')return `<path d="${arc(s)}" ${extra}/>`;if(s.type==='circle')return `<circle cx="${s.center[0]}" cy="${s.center[1]}" r="${Math.hypot(s.end[0]-s.center[0],s.end[1]-s.center[1])}" ${extra}/>`;if(s.type==='rect')return `<rect x="${Math.min(s.start[0],s.end[0])}" y="${Math.min(s.start[1],s.end[1])}" width="${Math.abs(s.end[0]-s.start[0])}" height="${Math.abs(s.end[1]-s.start[1])}" ${extra}/>`;return `<path d="M${s.start} L${s.end}" ${extra}/>`;}
function renderBoard(){const led=simulate(state).color;$('#pcb').innerHTML=`<defs><filter id="glow"><feGaussianBlur stdDeviation=".35"/></filter></defs><g transform="translate(${46.5+pan[0]} ${63.5+pan[1]}) scale(${zoom*(side==='B.Cu'?-1:1)} ${zoom}) translate(-46.5 -63.5)"><rect x="24" y="41" width="45" height="45" rx="4" fill="#183f37" stroke="#658b6e" stroke-width=".18"/>${showZones?board.zones.filter(z=>z.layer===side).map(z=>`<polygon points="${z.points.map(p=>p.join(',')).join(' ')}" fill="${net===z.net?'#dbeb9c':'#275c4b'}" opacity=".6"/>`).join(''):''}<g fill="none" stroke-linecap="round">${showTracks?board.tracks.filter(t=>t.layer===side).map(t=>shape(t,`stroke="${net===t.net?'#e8ff91':side==='F.Cu'?'#649777':'#66a7be'}" opacity="${net&&net!==t.net?'.12':'.65'}" stroke-width="${t.width}"`)).join(''):''}</g>${board.vias.map(v=>`<circle cx="${v.at[0]}" cy="${v.at[1]}" r="${v.size/2}" fill="${net===v.net?'#e8ff91':'#9ba77e'}"/><circle cx="${v.at[0]}" cy="${v.at[1]}" r="${v.drill/2}" fill="#101719"/>`).join('')}${board.components.map((c,i)=>{const rotation=c.at[2]||0,active=selected===c;return `<g class="footprint" data-index="${i}" transform="translate(${c.at[0]} ${c.at[1]}) rotate(${-rotation})"><title>${esc(c.ref+' · '+c.value)}</title>${c.layer===side?c.shapes.filter(s=>s.layer.endsWith('Fab')).map(s=>shape(s,'fill="#202c2b" stroke="#56625b" stroke-width=".1"')).join(''):''}${c.pads.filter(p=>p.layers.includes(side)||p.layers.includes('*.Cu')).map(p=>`<g transform="translate(${p.at[0]} ${p.at[1]}) rotate(${-(p.at[2]||rotation)+rotation})">${p.shape==='circle'?`<circle r="${p.size[0]/2}"`: `<rect x="${-p.size[0]/2}" y="${-p.size[1]/2}" width="${p.size[0]}" height="${p.size[1]}" rx="${p.shape==='roundrect'?'.12':'0'}"`} fill="${net===p.net?'#e8ff91':'#c7b480'}"/>${p.drill?`<circle r="${p.drill/2}" fill="#101719"/>`:''}</g>`).join('')}${c.layer===side?c.shapes.filter(s=>s.layer.endsWith('SilkS')).map(s=>shape(s,'fill="none" stroke="#c8d5bb" stroke-width=".12"')).join(''):''}${active?'<circle r="3.1" fill="#d9f99d22" stroke="#d9f99d" stroke-width=".18"/>':''}${c.ref.startsWith('LED')&&side==='F.Cu'?`<circle r="1" fill="${led}" opacity=".65" filter="url(#glow)"/><circle r=".4" fill="${led}"/>`:''}<circle r="${c.ref==='U7'?6:1.1}" fill="transparent"/>${showLabels&&!c.ref.includes('*')?`<text transform="rotate(${rotation}) ${side==='B.Cu'?'scale(-1 1)':''}" x="0" y="-1.7" text-anchor="middle" fill="${active?'#e8ff91':'#e0e9cc'}" font-size=".85" font-family="monospace">${esc(c.ref)}</text>`:''}</g>`}).join('')}<g fill="none" stroke="#99b79c" stroke-width=".12">${board.edges.map(s=>shape(s)).join('')}</g><path d="M25.4 48H32V42.25H34V50.2H25.4Z M61 42.2V51H67V53.1H58.8V42.2Z" fill="#101719"/><text x="46.5" y="57.5" text-anchor="middle" fill="#a6bda5" font-size="1.5" font-family="monospace" ${side==='B.Cu'?'opacity="0"':''}>noware / v1.1</text>${highlightOverlay(board,designKind,side)}</g>`;
$('#zoom').textContent=Math.round(zoom*100)+'%';document.querySelectorAll('[data-index]').forEach(el=>el.onclick=e=>{e.stopPropagation();if(!dragged)select(board.components[Number(el.dataset.index)],true)});}
function select(c,toggle=false){selected=toggle&&selected===c?null:c;list($('#search').value);inspect();renderBoard();}
function inspect(){const c=selected;$('#inspector').innerHTML=c?`<div class="inspect-title"><div><span class="tiny-label">COMPONENT INSPECTOR</span><h3>${esc(c.ref)} <span>${esc(c.value)}</span></h3></div><div class="inspect-actions"><button id="inspect-3d" class="inspect-3d">View in 3D</button><span class="badge">${c.layer==='F.Cu'?'FRONT':'BACK'}</span><button id="clear-component" aria-label="Clear component selection" title="Clear selection (Escape)">×</button></div></div><div class="inspect-details"><span>Position <strong>${c.at[0].toFixed(2)}, ${c.at[1].toFixed(2)} mm</strong></span><span>Rotation <strong>${c.at[2]||0}°</strong></span><span>Pads <strong>${c.pads.length}</strong></span></div><div class="pins">${c.pads.filter(p=>p.net!=='0').map(p=>`<button data-net="${p.net}" title="Highlight connected traces">${esc(p.number)} <span>${esc(board.nets[p.net]||'Unconnected')}</span></button>`).join('')}</div><p class="footprint-name">${esc(c.footprint)}</p>`:`<div class="inspect-empty"><span>⌖</span><div><h3>Every connection has a story.</h3><p>Select a component to see its pins, position, and connected nets.</p></div></div>`;$('#inspect-3d')?.addEventListener('click',()=>showLibrary(selected?.ref));$('#clear-component')?.addEventListener('click',()=>select(null));document.querySelectorAll('[data-net]').forEach(el=>el.onclick=()=>setNet(el.dataset.net));}
function setNet(n){net=n;$('#net').value=n;$('#net-count').textContent=n?`${board.tracks.filter(t=>t.net===n).length} traces · ${board.components.filter(c=>c.pads.some(p=>p.net===n)).length} components`:`${board.tracks.length} routed traces · ${board.vias.length} vias`;renderBoard();}
const controls=[['tvoc','Volatile compounds','ppb',0,5500,10],['co2','True CO₂','ppm',400,5000,10],['brightness','LED brightness','%',0,100,1]];
$('#sliders').innerHTML=controls.map(([key,label,unit,min,max,step])=>`<div class="slider-control" id="control-${key}"><label for="${key}">${label} <span><output id="value-${key}"></output> ${unit}</span></label><input id="${key}" type="range" min="${min}" max="${max}" step="${step}"><div class="range-label"><span>${min}</span><span>${max.toLocaleString()} ${unit}</span></div></div>`).join('');
function modelComparison(){
 const pro=state.model==='pro';
 $('#model-comparison').innerHTML=`<details class="comparison" open><summary>Base vs Pro <span>What's different?</span></summary><table><thead><tr><th>Capability</th><th class="${!pro?'chosen':''}">Base</th><th class="${pro?'chosen':''}">Pro</th></tr></thead><tbody><tr><td>VOCs + estimated CO₂</td><td>ENS161</td><td>ENS161</td></tr><tr><td>Temperature + humidity</td><td>ENS210</td><td>SCD41</td></tr><tr class="pro-feature"><td>Direct CO₂ measurement</td><td>—</td><td>SCD41</td></tr><tr class="pro-feature"><td>Ambient light + auto dim</td><td>—</td><td>VCNL4040</td></tr><tr><td>LED color source</td><td>VOC</td><td>Worse of VOC / CO₂</td></tr></tbody></table><div class="sensor-links"><span>HIGHLIGHT ON THIS PCB</span><button data-sensor="U2">⌖ ENS161 · shared</button><button data-sensor="U10">⌖ ENS210 · Base only</button></div><p class="pro-board-note">SCD41 and VCNL4040 are Pro-only parts, absent from this Base PCB. Pro simulation uses virtual CO₂ input; auto dimming is not simulated.</p></details>`;
 document.querySelectorAll('[data-sensor]').forEach(el=>el.onclick=()=>{side='F.Cu';$('#front').classList.add('active');$('#back').classList.remove('active');pan=[0,0];zoom=1;setNet('');select(parts.find(c=>c.ref===el.dataset.sensor));$('#pcb').scrollIntoView({behavior:'smooth',block:'center'})});
}
function update(){const s=simulate(state);modelComparison();for(const [key]of controls){$('#'+key).value=state[key];$('#value-'+key).textContent=state[key].toLocaleString()}$('#model').value=state.model;$('#power').checked=state.power;$('#co2').disabled=state.model==='base';$('#control-co2').classList.toggle('disabled',state.model==='base');$('#led').style.setProperty('--led',s.color);$('#rating').textContent=state.power?s.rating:'Powered off';$('#driver').textContent=state.power?`${s.driver} drives the color · Level ${s.severity}`:'No LED output';$('#voc').textContent=s.voc;$('#carbon').textContent=state.model==='pro'?s.carbon:'—';$('#sim-note').textContent=`Behavioral preview of firmware thresholds and target LED hue. Brightness is a manual preview. ${state.model==='pro'?'Pro sensor inputs are virtual; the displayed PCB is Base. ':''}No circuit solver, firmware execution, or live device connection.`;try{localStorage.setItem('aircube-sim',JSON.stringify(state))}catch{}renderBoard();}
for(const [key]of controls)$('#'+key).oninput=e=>{state[key]=Number(e.target.value);update()};$('#model').onchange=e=>{state.model=e.target.value;update()};$('#power').onchange=e=>{state.power=e.target.checked;update()};$('#reset').onclick=()=>{state={...defaults};update()};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{Object.assign(state,({fresh:{tvoc:20,co2:450},busy:{tvoc:350,co2:1600},cooking:{tvoc:1800,co2:1100}})[b.dataset.preset]);update()});
$('#search').oninput=e=>list(e.target.value);$('#net').onchange=e=>setNet(e.target.value);for(const [id,layer]of [['front','F.Cu'],['back','B.Cu']])$('#'+id).onclick=()=>{side=layer;$('#front').classList.toggle('active',side==='F.Cu');$('#back').classList.toggle('active',side==='B.Cu');renderBoard()};$('#tracks').onchange=e=>{showTracks=e.target.checked;renderBoard()};$('#labels').onchange=e=>{showLabels=e.target.checked;renderBoard()};$('#zones').onchange=e=>{showZones=e.target.checked;renderBoard()};function changeZoom(z){zoom=Math.max(.6,Math.min(5,z));renderBoard()}$('#plus').onclick=()=>changeZoom(zoom*1.2);$('#minus').onclick=()=>changeZoom(zoom/1.2);$('#fit').onclick=()=>{pan=[0,0];changeZoom(1)};$('#pcb').addEventListener('wheel',e=>{e.preventDefault();changeZoom(zoom*(e.deltaY<0?1.1:1/1.1))},{passive:false});let drag=null,dragged=false;$('#pcb').onpointerdown=e=>{drag=[e.clientX,e.clientY,...pan];dragged=false};window.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag[0],dy=e.clientY-drag[1];if(Math.hypot(dx,dy)>4){dragged=true;const scale=59/Math.min($('#pcb').clientWidth,$('#pcb').clientHeight);pan=[drag[2]+dx*scale,drag[3]+dy*scale];renderBoard()}});window.addEventListener('pointerup',()=>{drag=null});window.addEventListener('pointercancel',()=>{drag=null});
$('#pcb').addEventListener('click',e=>{if(!dragged&&!e.target.closest('.footprint'))select(null)});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected&&!document.querySelector('#component-library'))select(null)});
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({schema:1,sourceCommit:board.commit,inputs:state,result:simulate(state),selectedComponent:selected?.ref,selectedNet:board.nets[net],simulation:'Behavioral target LED preview; not an electrical solver'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='noware-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
list();inspect();update();

$('#signout').onclick=async()=>{const r=await fetch('/api/auth?action=logout',{method:'POST'});if(r.ok)location.replace('/login');else alert('Sign-out failed. Please try again.')};

function showDesignOnBoard(kind){
 designKind=kind;
 if(kind){side='F.Cu';pan=[0,0];zoom=1;net='';$('#net').value='';$('#front').classList.add('active');$('#back').classList.remove('active');selected=parts.find(c=>c.ref==='U7');list($('#search').value);inspect();setNet('');}
 const note=$('#design-board-note');note.hidden=!kind;
 if(kind){const d=designHighlights[kind];note.innerHTML=`<strong>${d.title}</strong><p>${d.note}</p><div>${d.parts.map(p=>`<button data-highlight-part="${p.ref}"><i style="background:${p.color}"></i>${p.ref} · ${p.action}</button>`).join('')}</div>${kind==='cellular'?'<span class="proposed-addition">+ Modem · SIM · antenna · modem supply — proposed additions, placement not defined</span>':''}`;note.querySelectorAll('[data-highlight-part]').forEach(b=>b.onclick=()=>select(parts.find(c=>c.ref===b.dataset.highlightPart)));}
 renderBoard();
}
const designLab=mountDesignLab({board,onConnectionChange:showDesignOnBoard,selectPart:ref=>{const part=parts.find(c=>c.ref===ref);if(part){side='F.Cu';$('#front').classList.add('active');$('#back').classList.remove('active');pan=[0,0];zoom=1;select(part)}}});

async function showLibrary(ref){const button=$('#open-library');button.disabled=true;try{const {openComponentLibrary}=await import('./component-library.js');openComponentLibrary({board,initialRef:ref,onTryConnection:kind=>designLab.setConnection(kind),onLocate:ref=>{const c=parts.find(p=>p.ref===ref);if(c){side=c.layer==='B.Cu'?'B.Cu':'F.Cu';$('#front').classList.toggle('active',side==='F.Cu');$('#back').classList.toggle('active',side==='B.Cu');pan=[0,0];zoom=1;select(c);$('#pcb').scrollIntoView({behavior:'smooth',block:'center'})}}});}catch{alert('Component library could not load. Please refresh and try again.')}finally{button.disabled=false}}
$('#open-library').onclick=()=>showLibrary(selected?.ref);

mountShowcase();
