import './showcase.css';
import {chapters,storyPose} from './config.js';
export function mountShowcase(){
 const section=document.createElement('section');section.className='hardware-story';section.id='hardware';section.setAttribute('aria-label','Explore AirCube hardware');
 section.innerHTML=`<div class="hardware-sticky"><div class="hardware-topline"><span>NOWARE / OBJECT STUDIES</span><span>001 — AIRCUBE BASE</span></div><div class="hardware-layout"><div class="hardware-copy"><div class="hardware-kicker"><span></span> SMALL HARDWARE. REAL POSSIBILITY.</div><h2>See the air.<br><em>Know your<br class="desktop-break"> hardware.</em></h2><p class="hardware-intro">A quiet signal. A thoughtful little object.<br>Explore what happens beneath the surface.</p><a class="hardware-cta" href="#playground">Explore the board <span>↗</span></a><div class="hardware-chapter"><span id="hardware-number">01 / 05</span><h3 id="hardware-title">A little presence.</h3><p id="hardware-description">A clearer picture of the air around you. Explore the hardware behind a simple signal.</p></div></div><div class="hardware-visual"><div class="hardware-model-meta"><span>49 × 49 mm footprint</span><span>Open-source hardware</span></div><img class="hardware-poster" src="/showcase/poster.webp" alt="AirCube Base, a softly illuminated translucent top on a warm white rounded enclosure" width="1100" height="1000" fetchpriority="high"><div class="hardware-canvas"></div><div class="hardware-anchors"><button data-anchor="diffuser" data-part="diffuser" hidden>Diffuser</button><button data-anchor="U2" data-part="U2" hidden>ENS161</button><button data-anchor="pcb" data-part="pcb" hidden>Base PCB</button></div><div class="hardware-view-tools"><span>↔ Drag to rotate</span><button data-action="reset">Reset view ↺</button></div><p class="hardware-fallback" role="status">Loading the interactive model…</p></div></div><div class="hardware-controls"><div class="hardware-assembly"><button data-action="explode" aria-pressed="false">Explore inside <span>↗</span></button><button data-action="airflow" aria-pressed="false">Airflow <span>○</span></button></div><div class="hardware-air"><span class="hardware-demo">INTERACTIVE DEMO</span><div role="group" aria-label="Air quality demonstration"><button data-air="good" aria-pressed="true"><i></i>Good</button><button data-air="attention" aria-pressed="false"><i></i>Needs attention</button><button data-air="poor" aria-pressed="false"><i></i>Poor</button></div><span class="hardware-status" role="status">Air quality: good.</span></div></div><p class="hardware-flow-note" hidden>Ambient airflow · illustration</p><nav class="hardware-chapters" aria-label="Hardware story">${['Meet the hardware','Explore inside','Follow the air','Read the light','Keep exploring'].map((t,i)=>`<button data-chapter="${i}" aria-current="${i===0?'step':'false'}"><span>0${i+1}</span>${t}</button>`).join('')}<button data-action="scroll" hidden>Resume scroll story ↓</button></nav><div class="hardware-bottomline"><span>BUILT FROM REAL CAD. MADE FOR CURIOSITY.</span><a href="/showcase/README.md" target="_blank" rel="noreferrer">Model & source notes ↗</a></div></div>`;
 document.querySelector('header').after(section);
 // Keep the engineering tools available on demand, without a PCB list filling
 // the landing page. Existing event handlers and DOM references remain intact.
 const playground=document.createElement('details');playground.id='playground';playground.className='hardware-playground';
 playground.innerHTML='<summary>Hardware playground <span>Open the engineering tools ↗</span></summary>';
 const intro=document.querySelector('.intro');intro.before(playground);
 playground.append(intro,document.querySelector('main'));
 section.querySelector('.hardware-cta').addEventListener('click',()=>{playground.open=true;});
 const $=s=>section.querySelector(s),reduced=matchMedia('(prefers-reduced-motion: reduce)'),mobile=matchMedia('(max-width: 700px)');
 const state={progress:0,air:'good',selected:null,mode:reduced.matches||mobile.matches?'manual':'scroll',exploded:false,airflow:null,rotation:0,tilt:0,dragging:false,reduced:reduced.matches};let scene,dead=false;
 function sync(){const pose=storyPose(state.progress),expanded=state.mode==='scroll'?pose.explode>.5:state.exploded;section.dataset.mode=state.mode;section.dataset.chapter=pose.chapter;section.dataset.selected=state.selected||'';section.style.setProperty('--air-color',({good:'#7dbb70',attention:'#cea338',poor:'#d26c5c'})[state.air]);$('#hardware-number').textContent=`0${pose.chapter+1} / 05`;$('#hardware-title').textContent=chapters[pose.chapter][1];$('#hardware-description').textContent=chapters[pose.chapter][2];$('[data-action="explode"]').innerHTML=(expanded?'Reassemble':'Explore inside')+' <span>↗</span>';$('[data-action="explode"]').setAttribute('aria-pressed',expanded);const flow=state.airflow??pose.flow;$('[data-action="airflow"]').setAttribute('aria-pressed',flow);$('.hardware-flow-note').hidden=!flow;$('[data-action="scroll"]').hidden=state.mode==='scroll'||mobile.matches||state.reduced;section.querySelectorAll('[data-chapter]').forEach(b=>b.setAttribute('aria-current',+b.dataset.chapter===pose.chapter?'step':'false'));scene?.wake();}
 function select(name){state.selected=name;section.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.part===name));sync()}
 section.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.air){state.air=b.dataset.air;section.querySelectorAll('button[data-air]').forEach(el=>el.setAttribute('aria-pressed',el===b));$('.hardware-status').textContent='Air quality: '+({good:'good',attention:'needs attention',poor:'poor'})[state.air]+'.';}
 if(b.dataset.part)select(b.dataset.part);
 if(b.dataset.chapter){const i=+b.dataset.chapter;state.mode='manual';state.progress=i===4?1:(i+.5)/5;state.exploded=i===1||i===2;state.airflow=i===2;}
 if(b.dataset.action==='explode'){state.exploded=!(state.mode==='scroll'?storyPose(state.progress).explode>.5:state.exploded);state.mode='manual';state.progress=state.exploded?.3:.05;}
 if(b.dataset.action==='airflow')state.airflow=!(state.airflow??storyPose(state.progress).flow);
 if(b.dataset.action==='reset'){state.rotation=0;state.tilt=0;}
 if(b.dataset.action==='scroll'){state.mode='scroll';state.airflow=null;scroll();}sync();});
 function scroll(){if(state.mode!=='scroll')return;const r=section.getBoundingClientRect();state.progress=Math.max(0,Math.min(1,-r.top/(section.offsetHeight-innerHeight)));sync()}
 function motion(){state.reduced=reduced.matches;if(state.reduced||mobile.matches){state.mode='manual';state.progress=0;state.exploded=false;}sync()}
 window.addEventListener('scroll',scroll,{passive:true});reduced.addEventListener('change',motion);mobile.addEventListener('change',motion);sync();
 import('./scene.js').then(({createScene})=>createScene($('.hardware-canvas'),state,select,()=>{if(dead)return;section.classList.add('hardware-ready');$('.hardware-fallback').hidden=true;})).then(s=>{scene=s;if(dead)s.dispose();else sync()}).catch(error=>{console.error('Hardware showcase:',error);section.classList.add('hardware-unavailable');$('.hardware-fallback').textContent='3D is unavailable. The product preview and hardware playground remain available.';});
 const cleanup=()=>{dead=true;scene?.dispose();window.removeEventListener('scroll',scroll);reduced.removeEventListener('change',motion);mobile.removeEventListener('change',motion)};window.addEventListener('pagehide',event=>{if(!event.persisted)cleanup()});return cleanup;
}
