import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {settings,components,storyPose} from './config.js';
import {makeAirflow} from './airflow.js';
export async function createScene(host,state,onSelect,onReady){
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<600?settings.pixelRatio.mobile:settings.pixelRatio.desktop));renderer.setClearColor('#f1f0ec',0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','AirCube Base 3D model. Drag horizontally to rotate; use the controls to explore.');renderer.domElement.setAttribute('role','img');
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(settings.fov,1,.1,600);camera.position.set(...settings.camera);camera.lookAt(...settings.target);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.65;room.dispose();pmrem.dispose();
 scene.add(new T.HemisphereLight('#fffef7','#b0b6ba',.65));const key=new T.DirectionalLight('#fffaf0',2);key.position.set(-45,90,45);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-85,right:85,top:85,bottom:-85,near:1,far:250});key.shadow.normalBias=.15;key.shadow.bias=-.0002;key.shadow.radius=4;scene.add(key);const fill=new T.DirectionalLight('#e2ebf5',.65);fill.position.set(60,35,-60);scene.add(fill);
 const ground=new T.Mesh(new T.PlaneGeometry(500,500),new T.ShadowMaterial({opacity:.075}));ground.rotation.x=-Math.PI/2;ground.position.y=-.15;ground.receiveShadow=true;scene.add(ground);
 const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=128;const ctx=glowCanvas.getContext('2d'),gr=ctx.createRadialGradient(64,64,0,64,64,64);gr.addColorStop(0,'#ffffff');gr.addColorStop(1,'#ffffff00');ctx.fillStyle=gr;ctx.fillRect(0,0,128,128);const glowTexture=new T.CanvasTexture(glowCanvas);const spill=new T.Mesh(new T.PlaneGeometry(85,85),new T.MeshBasicMaterial({map:glowTexture,transparent:true,opacity:.1,depthWrite:false,color:settings.colors.good}));spill.rotation.x=-Math.PI/2;spill.position.y=.02;scene.add(spill);
 let disposed=false,model;try{model=(await new GLTFLoader().loadAsync('/showcase/aircube-base.glb')).scene;}catch(e){renderer.dispose();env.dispose();host.replaceChildren();throw e;}
 const pivot=new T.Group();pivot.add(model);scene.add(pivot);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});
 const parts=Object.fromEntries(['housing','diffuser','airwall','pcb','U2','U10','U7'].map(n=>[n,model.getObjectByName(n)]));
 const diffuser=parts.diffuser;diffuser.material=new T.MeshPhysicalMaterial({color:'#e1f0d5',roughness:.5,metalness:0,transmission:.08,thickness:1.3,ior:1.45,emissive:settings.colors.good,emissiveIntensity:.28});
 diffuser.material.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vShellPosition;').replace('#include <begin_vertex>','#include <begin_vertex>\nvShellPosition = position;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vShellPosition;').replace('#include <emissivemap_fragment>','#include <emissivemap_fragment>\nfloat diffusion = 1.0 - smoothstep(10.0, 33.0, vShellPosition.y);\ntotalEmissiveRadiance *= 0.35 + diffusion * 1.5;\ndiffuseColor.rgb *= 0.995 + 0.005 * sin(vShellPosition.y * 35.0);');};
 const bases=new Map();model.traverse(o=>{if(o.material?.emissive)bases.set(o,o.material.emissive.clone())});
 const flow=makeAirflow();pivot.add(flow.group);let raf=0,visible=true,previous=performance.now(),time=0,currentExplode=0,rotation=0,tilt=0;const tint=new T.Color(settings.colors[state.air]);
 const labels=[...host.parentElement.querySelectorAll('[data-anchor]')];
 function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;const distance=innerWidth<650?1.15:1;camera.position.set(...settings.camera).multiplyScalar(distance);camera.lookAt(...settings.target);camera.updateProjectionMatrix();wake();}
 function frame(now){raf=0;if(disposed||!visible||document.hidden)return;const dt=Math.max(0,Math.min((now-previous)/1000,.05));previous=now;time+=dt;const pose=storyPose(state.progress);const target=state.mode==='scroll'?pose.explode:state.exploded?1:0;currentExplode=state.reduced?target:T.MathUtils.damp(currentExplode,target,5,dt);for(const [name,offset]of Object.entries(settings.explode))parts[name].position.y=offset*currentExplode;
 tint.lerp(new T.Color(settings.colors[state.air]),state.reduced?1:1-Math.exp(-dt*4));diffuser.material.emissive.copy(tint);diffuser.material.color.copy(new T.Color('#faf8eb').lerp(tint,.55));diffuser.material.emissiveIntensity=.36*(1-currentExplode*.5);spill.material.color.copy(tint);spill.material.opacity=.14*(1-currentExplode*.8);
 rotation=state.reduced?state.rotation:T.MathUtils.damp(rotation,state.rotation,8,dt);tilt=state.reduced?state.tilt:T.MathUtils.damp(tilt,state.tilt,8,dt);pivot.rotation.y=rotation+(!state.reduced&&!state.dragging&&state.rotation===0?Math.sin(time*.22)*.035:0);pivot.rotation.x=tilt;pivot.position.y=state.reduced?0:(1-currentExplode)*(1.2+Math.sin(time*.8)*.45);
 for(const [o,base]of bases){if(o===diffuser)continue;let p=o,selected=false;while(p){if(p.name===state.selected)selected=true;p=p.parent}o.material.emissive.copy(selected?new T.Color('#6c9470').multiplyScalar(.25):base);}
 flow.group.position.y=currentExplode*settings.explode.pcb;flow.update(time,tint,state.reduced);
 const sensor=parts.U2;if(flow.group.visible)sensor.traverse(o=>{if(o.material?.emissive)o.material.emissive.copy(tint).multiplyScalar(.22)});
 const distance=(innerWidth<650?1.15:1)*(1+currentExplode*.2);camera.position.set(...settings.camera).multiplyScalar(distance);camera.lookAt(0,19+currentExplode*14,0);
 scene.updateMatrixWorld(true);for(const label of labels){const o=parts[label.dataset.anchor];const pos=new T.Box3().setFromObject(o).getCenter(new T.Vector3()).project(camera);label.style.left=(pos.x*.5+.5)*host.clientWidth+'px';label.style.top=(-pos.y*.5+.5)*host.clientHeight+'px';label.hidden=currentExplode<.65;}
 renderer.render(scene,camera);host.dataset.explode=currentExplode.toFixed(2);host.dataset.flow=String(flow.group.visible);host.dataset.air=state.air;host.dataset.drawCalls=renderer.info.render.calls;host.dataset.triangles=renderer.info.render.triangles;
 if(!state.reduced||Math.abs(currentExplode-target)>.001)raf=requestAnimationFrame(frame);
 }
 function wake(){if(!raf&&!disposed&&visible&&!document.hidden){previous=performance.now();raf=requestAnimationFrame(frame)}}
 const observer=new ResizeObserver(resize);observer.observe(host);const intersection=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible)wake();else{cancelAnimationFrame(raf);raf=0}},{rootMargin:'50px'});intersection.observe(host);
 const visibility=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else wake()};document.addEventListener('visibilitychange',visibility);
 let drag=null;const canvas=renderer.domElement;
 const down=e=>{drag={x:e.clientX,y:e.clientY,r:state.rotation,t:state.tilt,moved:false};state.dragging=true;canvas.setPointerCapture(e.pointerId);wake()};
 const move=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)>5)drag.moved=true;if(e.pointerType==='touch'&&Math.abs(dy)>Math.abs(dx))return;state.rotation=Math.max(-1.5,Math.min(1.5,drag.r+dx*.008));if(e.pointerType!=='touch')state.tilt=Math.max(-.18,Math.min(.3,drag.t+dy*.003));wake()};
 const up=e=>{if(drag&&!drag.moved){const r=canvas.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);let hit=ray.intersectObject(model,true)[0]?.object;while(hit&&!components[hit.name])hit=hit.parent;if(hit)onSelect(hit.name)}drag=null;state.dragging=false;wake()};
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',()=>{drag=null;state.dragging=false});
 resize();wake();onReady();return {wake,dispose(){disposed=true;cancelAnimationFrame(raf);observer.disconnect();intersection.disconnect();document.removeEventListener('visibilitychange',visibility);scene.traverse(o=>{o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:o.material?[o.material]:[])m.dispose()});glowTexture.dispose();env.dispose();renderer.dispose();canvas.remove();}};
}
